import type { SpecResource } from "../../schema";
import type { TerraformFile, TerraformOutput, ServiceGenerator } from "./types";
import { groupResourcesByModule } from "./module-grouper";
import { generateProviderTf } from "./provider";
import { hclVariable, hclOutput } from "./hcl-utils";

// Service generators
import { generateVpcHcl } from "./services/vpc";
import { generateSubnetHcl } from "./services/subnet";
import { generateEc2Hcl } from "./services/ec2";
import { generateLambdaHcl } from "./services/lambda";
import { generateS3Hcl } from "./services/s3";
import { generateRdsHcl } from "./services/rds";
import { generateDynamoDbHcl } from "./services/dynamodb";
import { generateAlbHcl } from "./services/alb";
import { generateEcsHcl } from "./services/ecs";
import { generateSecurityGroupHcl } from "./services/security-group";
import { generateCloudFrontHcl } from "./services/cloudfront";
import { generateSqsHcl } from "./services/sqs";
import { generateSnsHcl } from "./services/sns";
import { generateDefaultHcl } from "./services/default";

/** Registry of dedicated service generators. */
const SERVICE_GENERATORS: Record<string, ServiceGenerator> = {
  vpc: generateVpcHcl,
  subnet: generateSubnetHcl,
  ec2: generateEc2Hcl,
  lambda: generateLambdaHcl,
  s3: generateS3Hcl,
  rds: generateRdsHcl,
  dynamodb: generateDynamoDbHcl,
  alb: generateAlbHcl,
  ecs: generateEcsHcl,
  securitygroup: generateSecurityGroupHcl,
  cloudfront: generateCloudFrontHcl,
  sqs: generateSqsHcl,
  sns: generateSnsHcl,
};

function getGenerator(type: string): ServiceGenerator {
  return SERVICE_GENERATORS[type.toLowerCase()] ?? generateDefaultHcl;
}

function fileHeader(moduleName: string): string {
  return [
    "# Generated by Cold Network Plane Studio",
    `# Module: ${moduleName}`,
    `# Generated at: ${new Date().toISOString()}`,
    "",
  ].join("\n");
}

/**
 * Analyze cross-module dependencies.
 * Returns which modules depend on which other modules.
 */
function analyzeDependencies(
  resources: SpecResource[],
  moduleMap: Map<string, string> // resource name → module name
): Map<string, Set<string>> {
  const deps = new Map<string, Set<string>>();

  for (const resource of resources) {
    const myModule = moduleMap.get(resource.name);
    if (!myModule) continue;

    // Check parent
    if (resource.parent) {
      const parentModule = moduleMap.get(resource.parent);
      if (parentModule && parentModule !== myModule) {
        if (!deps.has(myModule)) deps.set(myModule, new Set());
        deps.get(myModule)!.add(parentModule);
      }
    }

    // Check dependsOn
    for (const dep of resource.dependsOn ?? []) {
      const depModule = moduleMap.get(dep);
      if (depModule && depModule !== myModule) {
        if (!deps.has(myModule)) deps.set(myModule, new Set());
        deps.get(myModule)!.add(depModule);
      }
    }

    // Check connectTo
    for (const conn of resource.connectTo ?? []) {
      const connModule = moduleMap.get(conn);
      if (connModule && connModule !== myModule) {
        if (!deps.has(myModule)) deps.set(myModule, new Set());
        deps.get(myModule)!.add(connModule);
      }
    }
  }

  return deps;
}

/**
 * Generate modular Terraform from a list of spec resources.
 * Produces provider.tf, root main.tf/variables.tf/outputs.tf,
 * and modules/{category}/main.tf/variables.tf/outputs.tf per module.
 */
export function generateTerraformModular(
  resources: SpecResource[]
): TerraformOutput {
  const warnings: string[] = [];
  const files: TerraformFile[] = [];

  if (resources.length === 0) {
    return { files: [], warnings: [] };
  }

  // Group resources by module
  const moduleGroups = groupResourcesByModule(resources);

  // Build resource → module mapping for dependency analysis
  const resourceModuleMap = new Map<string, string>();
  for (const group of moduleGroups) {
    for (const r of group.resources) {
      resourceModuleMap.set(r.name, group.moduleName);
    }
  }

  // Analyze cross-module dependencies
  const moduleDeps = analyzeDependencies(resources, resourceModuleMap);

  // Track all variable names seen per module (dedup)
  const moduleVarNames = new Map<string, Set<string>>();

  // Generate per-module files
  for (const group of moduleGroups) {
    const mainBlocks: string[] = [fileHeader(group.moduleName)];
    const variableBlocks: string[] = [fileHeader(group.moduleName)];
    const outputBlocks: string[] = [fileHeader(group.moduleName)];
    const seenVars = new Set<string>();
    moduleVarNames.set(group.moduleName, seenVars);

    for (const resource of group.resources) {
      const generator = getGenerator(resource.type);
      const result = generator(resource);

      mainBlocks.push(result.mainBlock);
      mainBlocks.push("");

      // Deduplicate variables by extracting the variable name
      for (const vBlock of result.variableBlocks) {
        const match = vBlock.match(/^variable\s+"([^"]+)"/);
        const varName = match?.[1] ?? vBlock;
        if (!seenVars.has(varName)) {
          seenVars.add(varName);
          variableBlocks.push(vBlock);
          variableBlocks.push("");
        }
      }

      for (const oBlock of result.outputBlocks) {
        outputBlocks.push(oBlock);
        outputBlocks.push("");
      }
    }

    // Add module-level variables (project_name, environment)
    if (!seenVars.has("project_name")) {
      variableBlocks.push(hclVariable("project_name", "string", "Project name", '"cold-plane"'));
      variableBlocks.push("");
    }
    if (!seenVars.has("environment")) {
      variableBlocks.push(hclVariable("environment", "string", "Environment", '"dev"'));
      variableBlocks.push("");
    }

    const prefix = `modules/${group.moduleName}`;
    files.push({ path: `${prefix}/main.tf`, content: mainBlocks.join("\n") });
    files.push({ path: `${prefix}/variables.tf`, content: variableBlocks.join("\n") });
    files.push({ path: `${prefix}/outputs.tf`, content: outputBlocks.join("\n") });
  }

  // Generate root provider.tf
  files.unshift({ path: "provider.tf", content: generateProviderTf() });

  // Generate root variables.tf
  const rootVars = [
    fileHeader("root"),
    hclVariable("aws_region", "string", "AWS region", '"us-east-1"'),
    "",
    hclVariable("project_name", "string", "Project name", '"cold-plane"'),
    "",
    hclVariable("environment", "string", "Environment (dev, staging, prod)", '"dev"'),
    "",
  ];
  files.push({ path: "variables.tf", content: rootVars.join("\n") });

  // Generate root main.tf (calls child modules)
  const rootMain = [fileHeader("root")];
  for (const group of moduleGroups) {
    rootMain.push(`module "${group.moduleName}" {`);
    rootMain.push(`  source = "./modules/${group.moduleName}"`);
    rootMain.push("");
    rootMain.push("  project_name = var.project_name");
    rootMain.push("  environment  = var.environment");

    // Pass cross-module references
    const deps = moduleDeps.get(group.moduleName);
    if (deps) {
      rootMain.push("");
      // If this module depends on networking, pass common networking outputs
      if (deps.has("networking")) {
        const netVars = moduleVarNames.get(group.moduleName);
        if (netVars?.has("vpc_id")) {
          rootMain.push(`  vpc_id     = module.networking.${findVpcOutputName(moduleGroups)}`);
        }
        if (netVars?.has("subnet_id")) {
          rootMain.push(`  subnet_id  = module.networking.${findSubnetOutputName(moduleGroups)}`);
        }
        if (netVars?.has("subnet_ids")) {
          rootMain.push(`  subnet_ids = [module.networking.${findSubnetOutputName(moduleGroups)}]`);
        }
        if (netVars?.has("security_group_ids")) {
          // Try security module first, then networking
          const secGroup = moduleGroups.find((g) => g.moduleName === "security");
          if (secGroup) {
            rootMain.push(`  security_group_ids = [module.security.${findSgOutputName(moduleGroups)}]`);
          } else {
            const netSgOutput = findSgOutputName(moduleGroups);
            if (netSgOutput) {
              rootMain.push(`  security_group_ids = [module.networking.${netSgOutput}]`);
            }
          }
        }
      }
    }

    rootMain.push("}");
    rootMain.push("");
  }
  files.push({ path: "main.tf", content: rootMain.join("\n") });

  // Generate root outputs.tf (forward key module outputs)
  const rootOutputs = [fileHeader("root")];
  for (const group of moduleGroups) {
    rootOutputs.push(`# --- ${group.moduleName} outputs ---`);
    // Forward a representative output per module
    rootOutputs.push(
      hclOutput(
        `${group.moduleName}_module`,
        `module.${group.moduleName}`,
        `All outputs from ${group.moduleName} module`
      )
    );
    rootOutputs.push("");
  }
  files.push({ path: "outputs.tf", content: rootOutputs.join("\n") });

  return { files, warnings };
}

/** Find the first VPC output name in the networking module. */
function findVpcOutputName(
  groups: { moduleName: string; resources: SpecResource[] }[]
): string {
  const netGroup = groups.find((g) => g.moduleName === "networking");
  if (!netGroup) return "vpc_id";
  const vpc = netGroup.resources.find((r) => r.type === "vpc");
  if (!vpc) return "vpc_id";
  return `${vpc.name.replace(/[^a-zA-Z0-9_]/g, "_")}_id`;
}

/** Find the first subnet output name in the networking module. */
function findSubnetOutputName(
  groups: { moduleName: string; resources: SpecResource[] }[]
): string {
  const netGroup = groups.find((g) => g.moduleName === "networking");
  if (!netGroup) return "subnet_id";
  const subnet = netGroup.resources.find((r) => r.type === "subnet");
  if (!subnet) return "subnet_id";
  return `${subnet.name.replace(/[^a-zA-Z0-9_]/g, "_")}_id`;
}

/** Find the first security group output name. */
function findSgOutputName(
  groups: { moduleName: string; resources: SpecResource[] }[]
): string {
  // Check security module first
  for (const g of groups) {
    const sg = g.resources.find((r) => r.type === "securitygroup");
    if (sg) return `${sg.name.replace(/[^a-zA-Z0-9_]/g, "_")}_id`;
  }
  return "sg_id";
}

// Re-export types for external consumers
export type { TerraformFile, TerraformOutput } from "./types";
