import type { SpecResource } from "../schema";

/**
 * Map of spec resource types to Terraform resource type strings.
 */
const TERRAFORM_TYPE_MAP: Record<string, string> = {
  vpc: "aws_vpc",
  subnet: "aws_subnet",
  router: "aws_route_table",
  firewall: "aws_network_firewall_firewall",
  gateway: "aws_internet_gateway",
  nat: "aws_nat_gateway",
  securitygroup: "aws_security_group",
  routetable: "aws_route_table",
  loadbalancer: "aws_lb",
  vpn: "aws_vpn_gateway",
  peering: "aws_vpc_peering_connection",
  endpoint: "aws_vpc_endpoint",
  dns: "aws_route53_zone",
  server: "aws_instance",
  switch: "aws_network_interface",
};

/**
 * Sanitize a resource name for use as a Terraform identifier.
 */
function terraformName(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, "_");
}

/**
 * Generate Terraform HCL for a single resource.
 */
function generateResourceBlock(resource: SpecResource): string {
  const tfType = TERRAFORM_TYPE_MAP[resource.type.toLowerCase()];
  const tfName = terraformName(resource.name);

  if (!tfType) {
    return `# Unsupported resource type: ${resource.type} (${resource.name})\n`;
  }

  const lines: string[] = [];
  lines.push(`resource "${tfType}" "${tfName}" {`);

  // Add tags
  lines.push(`  tags = {`);
  lines.push(`    Name = "${resource.name}"`);
  if (resource.parent) {
    lines.push(`    Parent = "${resource.parent}"`);
  }
  lines.push(`  }`);

  // Add properties as comments (actual HCL mapping is generator-specific)
  const props = resource.properties;
  if (Object.keys(props).length > 0) {
    lines.push("");
    lines.push("  # Properties from spec:");
    for (const [key, value] of Object.entries(props)) {
      const val = typeof value === "string" ? `"${value}"` : String(value);
      lines.push(`  # ${key} = ${val}`);
    }
  }

  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

export interface TerraformOutput {
  /** The main.tf content. */
  mainTf: string;
  /** Warnings for unsupported types. */
  warnings: string[];
}

/**
 * Generate Terraform HCL from a list of parsed spec resources.
 */
export function generateTerraform(resources: SpecResource[]): TerraformOutput {
  const warnings: string[] = [];
  const blocks: string[] = [];

  blocks.push("# Generated by Cold Network Plane");
  blocks.push(`# Resources: ${resources.length}`);
  blocks.push(`# Generated at: ${new Date().toISOString()}`);
  blocks.push("");

  for (const resource of resources) {
    const tfType = TERRAFORM_TYPE_MAP[resource.type.toLowerCase()];
    if (!tfType) {
      warnings.push(
        `Unsupported resource type "${resource.type}" for resource "${resource.name}" — skipped`
      );
    }
    blocks.push(generateResourceBlock(resource));
  }

  return {
    mainTf: blocks.join("\n"),
    warnings,
  };
}
